---
- name: Include {{ ansible_os_family }} specific variables.
  include_vars: "{{ ansible_os_family | lower }}-os.yml"

- name: Include {{ ansible_os_family }} specific tasks.
  include_tasks: "{{ ansible_os_family | lower }}-setup.yml"

- name: Install Anydesk.
  package:
    name:   "{{ anydesk_packages }}"
    state:  "{{ anydesk_packages_state }}"

- name: Include {{ ansible_os_family }} post-installation tasks.
  include_tasks: "{{ ansible_os_family | lower }}-postinstall.yml"
