# Dependencies
dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
dependencies_status: present

# Debian/ubuntu variables.
docker_apt_key: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
docker_apt_key_status: present

docker_apt_arch: amd64
docker_repo_url: https://download.docker.com/linux
docker_apt_release_channel: stable
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }}  {{ docker_apt_release_channel }}"
docker_apt_gpg_key: "{{ docker_repo_url }}/{{ ansible_distribution | lower }}/gpg"
docker_apt_repository_state: present